repo: "columns-of-cards"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Open+Sans"]', 'The Google Font, `Open Sans` is missing']
      - ['h2', 'An `<h2>` makes sense in this situation because this is part of a larger website.']
      - "h3"
      - "section"
      - "div"
      - 'a.btn.btn-small'
    search:
      - 'The Quest for Anderon'
      - 'Tabatha R. Barrett'
      - 'Dinosaur Knights'
      - 'Thomas S. Hedegaard'
      - 'The Black Dragon'
      - 'Hana Čejková'
      - 'Light Speed Laser Ships'
      - 'Felicity Orta Olivárez'

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', 0]
      - ['img', 'display', 'block']
      - ['.btn']
      - ['.btn:hover']
      - ['.btn-small']
    search:
      - "Open Sans"
      - "float: left"
      - "width: 25%"
      - "#f2f2f2"
      - "#333"
      - "#e2e2e2"
      - "#ccc"
      - "#aaa"
      - "#999"

screenshots:
  - path: "index.html"
    sizes: [1400]
